language: julia
os:
  - osx
  - linux
julia:
  - nightly
  - 0.4
  - 0.3
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Example"); Pkg.test("Example"; coverage=true)';
